config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord # rubocop:todo Style/Documentation
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord # rubocop:todo Style/Documentation
  belongs_to :author
end

app/models/user.rb
class User < ApplicationRecord # rubocop:todo Style/Documentation
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  enum role: { guest: 0, user: 1, admin: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base # rubocop:todo Style/Documentation
  before_action :authenticate_user!
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController # rubocop:todo Style/Documentation
  before_action :set_author, only: %i[show edit update destroy]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show; end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit; end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def author_params
    params.require(:author).permit(:name, :bio, :image_path)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController # rubocop:todo Style/Documentation
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :summary, :publication_year, :image_path, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_exist?(path)
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? path
    else
      Rails.application.assets_manifest.assets[path].present?
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper # rubocop:todo Style/Documentation
  def author_image_path(author)
    default_path = "author.png"
    path = author.image_path
    if !path.nil? && asset_exist?(path)
      path
    else
      default_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper # rubocop:todo Style/Documentation
  def book_image_path(book)
    default_path = "book.png"
    path = book.image_path
    if !path.nil? && asset_exist?(path)
      path
    else
      default_path
    end
  end
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= author.bio %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, size: "50" %>
  </div>

  <div class="mb-2">
    <%= form.label :image_path, style: "display: block" %>
    <%= form.text_field :image_path, size: "50" %>
  </div>

  <div class="mb-2">
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio, size: "50x5" %>
  </div>

  <div class="m-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="card">

  <div class="card-body">

    <h3>Editing Author</h3>

    <%= render "form", author: @author %>

    <br>

    <div>
      <%= link_to "Cancel", @author %>
    </div>

  </div>

</div>

app/views/authors/index.html.erb
<div id="authors">

  <ul class="list-group">
    <% @authors.each do |author| %>

      <%= render "layouts/_shared/list/author", { author: author } %>
      
    <% end %>
  </ul>

</div>

app/views/authors/new.html.erb
<div class="card">

  <div class="card-body">

    <h3>New Author</h3>

    <%= render "form", author: @author %>

    <br>

    <div>
      <%= link_to "Cancel", @author %>
    </div>

  </div>

</div>

app/views/authors/show.html.erb
<% author = @author %>
<%= render "layouts/_shared/detail/author/detail_card", { author: author } %>

app/views/layouts/_shared/detail/author/detail_card/_content.html.erb
<div id="books">
  <ul class="list-group" id="book_list">
    <% author.books.each do |book| %>
      
      <%= render "layouts/_shared/list/book", { book: book } %>

    <% end %>
  <ul>
</div>

app/views/layouts/_shared/detail/author/detail_card/_heading.html.erb
<div class="card mb-3" id="author_heading_card">

  <div class="row no-gutters" id="row.1">

    <div class="col-md-7" id="col.1">
      <%= render "layouts/_shared/detail/author/detail_card/heading/metadata_card", { author: author } %>
    </div>

    <div class="col-md-5" id="col.2">
      <%= render "layouts/_shared/detail/author/detail_card/heading/author_user_card", { author: author } %>
    </div>

  </div>

</div>

app/views/layouts/_shared/detail/author/detail_card/heading/_author_user_card.html.erb
<% author_user = nil %>

<% if author_user %>

  <div class="card m-3" id="author_user">

    <div class="card-header text-right">

      <h7><%= current_user.email.split("@").first %> </h7>
      
      <span class="px-2" id="liked">
        <% if author_user.liked %>
          <i class="fa fa-heart fa-lg" aria-hidden="true"></i>
        <% else %>
          <i class="fa fa-heart-o fa-lg" aria-hidden="true"></i>
        <% end %>    
      </span>

      <span>
        <%= link_to '<button type="button" class="btn btn-sm btn-outline-secondary mr-2 my-sm-0">Edit</button>'.html_safe, edit_author_user_path(author_user) %>
      </span>

    </div>

    <div class="card-body">

      <% if author_user.notes != nil && author_user.notes.length > 0 %>

        <h6 class="card-title">Notes:</h6>

        <p class="card-text">
        <%= author_user.notes %>
        </p>

      <% end %>

    </div>
    
  </div>

<% end %>

app/views/layouts/_shared/detail/author/detail_card/heading/_metadata_card.html.erb
<div class="card m-3" id="author_metadata_card">

  <div class="row no-gutters" id="row.1">

    <div class="col-md-5" id="col.1">
      <%= render "layouts/_shared/detail/author/detail_card/heading/metadata_card/image", author: author %>
    </div>

    <div class="col-md-7" id="col.2">

      <div class="card-body" id="body">

        <%= render "layouts/_shared/detail/author/detail_card/heading/metadata_card/heading", author: author %>
      
        <%= render "layouts/_shared/detail/author/detail_card/heading/metadata_card/options", author: author %>

      </div>

    </div>

  </div>

</div>

app/views/layouts/_shared/detail/author/detail_card/heading/metadata_card/_heading.html.erb
<h3 class="card-title"><%= @author.name %></h3>

<p class="card-text" id="summary">

  <% if @author.bio == "" || @author.bio == nil %>
    author summary not found...
  <% else %>
    <%= simple_format(@author.bio.split("\n").first) %>
  <% end %>

</p>

<p class="card-text" id="db">

  <small class="text-muted">
    Created: <%= author.created_at.strftime("%Y %m %d") %>
  </small>

  <br>

  <small class="text-muted">
    Last updated: <%= author.updated_at.strftime("%Y %m %d") %>
  </small>

</p>

app/views/layouts/_shared/detail/author/detail_card/heading/metadata_card/_image.html.erb
<%= image_tag author_image_path(author), class:"card-img" %>

app/views/layouts/_shared/detail/author/detail_card/heading/metadata_card/_options.html.erb
<div id="options">

  <ul class="nav">

    <% if current_user != nil && current_user.role == "admin" %>

      <li class="nav-item">
        <%= link_to '<button type="button" class="btn btn-sm btn-outline-secondary mr-2 my-sm-0">Edit</button>'.html_safe, edit_author_path(@author) %>
      </li>
      
      <li class="nav-item">
        <%= button_to "Delete", @author, form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, :class => "btn btn-sm btn-outline-secondary mr-2 my-sm-0" %>
      </li>

    <% end %>

  </ul>

</div> 

app/views/layouts/_shared/detail/book/_detail_card.html.erb
<div class="card" id="book_detail_card">

  <div class="card-body">

    <%= render "layouts/_shared/detail/book/detail_card/heading", { book: book } %>

    <br>

    <%= render "layouts/_shared/detail/book/detail_card/content", { book: book } %>

  </div>
  
</div>

app/views/layouts/_shared/detail/book/detail_card/heading/_book_user_card.html.erb
<% book_user = nil %>

<% if book_user %>

  <div class="card m-3" id="book_user">

    <div class="card-header text-right">

      <h7><%= current_user.email.split("@").first %> </h7>
      
      <span class="px-2" id="liked">
        <% if book_user.liked %>
          <i class="fa fa-heart fa-lg" aria-hidden="true"></i>
        <% else %>
          <i class="fa fa-heart-o fa-lg" aria-hidden="true"></i>
        <% end %>
      </span>

      <span>
        <%= link_to '<button type="button" class="btn btn-sm btn-outline-secondary mr-2 my-sm-0">Edit</button>'.html_safe, edit_book_user_path(book_user) %>
      </span>

    </div>

    <div class="card-body">

      <h6 class="card-title">Status: <%= book_user.status.titleize %></h6>

      <p></p>

      <% if book_user.notes != nil && book_user.notes.length > 0 %>

        <h6 class="card-title">Notes:</h6>

        <p class="card-text">
          <%= book_user.notes %>
        </p>

      <% end %>

    </div>
  </div>

<% end %>

app/views/layouts/_shared/detail/book/detail_card/heading/_metadata_card.html.erb
<div class="card m-3" id="book_metadata_card">

  <div class="row no-gutters" id="row.1">

    <div class="col-md-5" id="col.1">
      <%= render "layouts/_shared/detail/book/detail_card/heading/metadata_card/image", { book: book } %>
    </div>

    <div class="col-md-7" id="col.2">

      <div class="card-body" id="body">

        <%= render "layouts/_shared/detail/book/detail_card/heading/metadata_card/heading", { book: book } %>
      
        <%= render "layouts/_shared/detail/book/detail_card/heading/metadata_card/options", { book: book } %>

      </div>

    </div>

  </div>

</div>

app/views/layouts/_shared/detail/book/detail_card/heading/metadata_card/_heading.html.erb
<h3 class="card-title"><%= book.title %></h3>

<h5>by <%= link_to book.author.name, book.author %></h5>

<p class="card-text" id="summary"></p>

<p class="card-text" id="db">

  <small class="text-muted">
    Created: <%= book.created_at.strftime("%Y %m %d") %>
  </small>

  <br>

  <small class="text-muted">
    Last updated: <%= book.updated_at.strftime("%Y %m %d") %>
  </small>
  
</p>

app/views/layouts/_shared/detail/book/detail_card/heading/metadata_card/_image.html.erb
<%= image_tag book_image_path(book), class:"card-img" %>

app/views/layouts/_shared/detail/book/detail_card/heading/metadata_card/_options.html.erb
<div id="options">

  <ul class="nav">

    <% if current_user != nil && current_user.role == "admin" %>

      <li class="nav-item">
        <%= link_to '<button type="button" class="btn btn-sm btn-outline-secondary mr-2 my-sm-0">Edit</button>'.html_safe, edit_book_path(book) %>
      </li>
      
      <li class="nav-item">
        <%= button_to "Delete", book, form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, :class => "btn  btn-sm btn-outline-secondary mr-2 my-sm-0" %>
      </li>

    <% end %>

  </ul>

</div>

app/views/layouts/_shared/list/_author.html.erb
<li class="list-group-item">

  <div class="row">

    <div class="col-9 d-flex align-items-center" id="col.1">
        
        <%= render "layouts/_shared/list/author/thumbnail", author: author %>
        
        <%= render "layouts/_shared/list/author/heading", author: author %>

    </div>

    <div class="col-3 text-right" id="col.2">
      
      <%= render "layouts/_shared/list/author/author_users", { author: author } %>

    </div>

  </div>
        
</li>

app/views/layouts/_shared/list/_book.html.erb
<li class="list-group-item">

  <div class="row">

    <div class="col-9 d-flex align-items-center" id="col.1">

        <%= render "layouts/_shared/list/book/thumbnail", book: book %>
        <%= render "layouts/_shared/list/book/heading", book: book %>
  
    </div>

    <div class="col-3 text-right" id="col.2">
      
      <%= render "layouts/_shared/list/book/book_users", { book: book } %>
    
    </div>

  </div>

</li>

app/views/layouts/_shared/list/book/_book_users.html.erb
<% book_user = nil %>
<% book_users = nil %>

<span id="book_users">

  <% if book_user == nil || book_user.liked != true %>

    <span class="px-2" id="liked">
      <i class="fa fa-heart-o" aria-hidden="true"></i>
    </span>

  <% else %>

    <span class="px-2" id="liked">
      <i class="fa fa-heart" aria-hidden="true"></i>
    </span>

  <% end %>

  <% if book_users == nil %>

    <span class="badge badge-primary badge-pill" id="badge">0</span>

  <% else %>
    <% liked_count = bookUser.where(:book_id => book.id, :liked => true).count %>
    <span class="badge badge-secondary badge-pill" id="badge"><%= liked_count %></span>

  <% end %>

  <br>

  <% if book_user != nil && book_user.status != "unknown" %>

    <span class="badge badge-secondary badge-pill" id="badge"><%= book_user.status.titleize %></span>

  <% end %>

</span>

app/views/layouts/_shared/list/book/_heading.html.erb
<div class="px-2">

  <%= link_to book.title, book, class: "list_link list_link_hover" %>
  <br>
  <small class="text-muted">
    <%= link_to book.author.name, book.author, class: "list_link list_link_hover" %>
  </small>

</div>

app/views/layouts/_shared/list/book/_thumbnail.html.erb
<div class="px-2" id="artist_thumbnail">
  <%= image_tag book_image_path(book), height: 40, width: 40 %>
</div>

app/views/layouts/application/main_navbar/_user.html.erb
<% if user_signed_in? %>

  <small class="text-muted">
    <a class="nav-link" href="/#"><%= current_user.email %> | <%= current_user.role %></a>
  </small>

  <%= button_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn btn btn-outline-success mr-2 my-sm-0" %>

<% end %>